### ISSUE TITLE
Initialize App with some pre made suggestions like the website

### ISSUE THREAD

**Issue by vishaldhiman** [vishaldhiman/vc_android_native#24]
see picture

![image](https://cloud.githubusercontent.com/assets/6261636/8508796/6fca824c-224d-11e5-8020-326345bbc2eb.png)

**Comment by xamguo** [comment]
Is there an API for this data?

**Comment by vishaldhiman** [comment]
Certain search keywords are special for example, "top trending" - that is,
these are hard coded for convenience. Just copy from the vchoose.us the
suggestions.

Vishal

**Comment by xamguo** [comment]
Get it~
