### ISSUE TITLE
Login Bug

### ISSUE THREAD

**Issue by xamguo** [vishaldhiman/vc_android_native#27]
When I try login vchoose though Postman, it worked out fine: http://vchoose.us/users/sign_in.json?email=867136922@qq.com&password=ty113113. However, when I try use Android to do the same thing, a error was threw.
It return 404 and said "message": "missing user_login parameter".
And sometimes return {"login":"","password":null}.
I wonder what happened. What is the difference between log in using Android and Postman.

**Comment by vishaldhiman** [comment]
Are you sure you are doing a HTTP POST and not a GET instead?

Vishal

**Comment by xamguo** [comment]
I pushed the latest code. The login goes wrong at line 158 in Login.java. And the post function is at line 78 in VcJsonReader.java
Could u help me see what is going wrong?

**Comment by xamguo** [comment]
![capture](https://cloud.githubusercontent.com/assets/10659678/8574181/415e704e-254a-11e5-9df8-2cb1f8c24d04.PNG)
