### ISSUE TITLE
User Info

### ISSUE THREAD

**Issue by xamguo** [vishaldhiman/vc_android_native#28]
http://vchoose.us/api/v1/public/user/38/details
This api returns data not in JSON format.
![capture_7_19 1](https://cloud.githubusercontent.com/assets/10659678/8768336/01638d72-2e31-11e5-913f-f20e76506ac2.PNG)

**Comment by vishaldhiman** [comment]
try .json at the end of URL.

Vishal

**Comment by xamguo** [comment]
Solved
