### ISSUE TITLE
API problem

### ISSUE THREAD

**Issue by xamguo** [vishaldhiman/vc_android_native#4]
All changes are uploaded, but there are few problems:
1. the auto complete API is working in post man but not in the browser nor our app.
2. The star rating is not in up-load mode, need more discussion.

**Comment by vishaldhiman** [comment]
What is the error message?

Vishal

**Comment by xamguo** [comment]
show u tomorrow, no error message.

Xiao Guo

> 在 2015年4月5日，下午7:48，Vishal Dhiman notifications@github.com 写道：
> 
> What is the error message?
> 
> Vishal

**Comment by vishaldhiman** [comment]
Here's how to fix it: Append the following to all calls.

&format=json

So for instance for for tag autocomplete, the call should be:
http://vchoose.us/api/v1/public/tag/autocomplete?term=v&format=json

(FYI, format=xml should also work)
